### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by zeroploitable** [ricardojoserf/adfsbrute#3] opened 2021-04-20 17:02 UTC
Hi,

I am using the following command:
python3 adfsbrute.py -t domain.com.lb -U spraying-list -p 'Password' -m 20 -M 30 -tp test123 -r False
The following error occurred after testing 30 emails approx successfully:

Traceback (most recent call last):                                                                                                                                                                           
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='**********', port=443): Max retries exceeded with url: /adfs/ls/?username=test%40*******b&wa=wsignin1.0&wtrealm=urn%3Afederation%3AMicrosoftOnline&wctx= (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))

**Comment by ricardojoserf** [comment] 2021-04-20 17:43
Hello @zeroploitable . Thank you for opening the issue and letting me know about the error. Could I know if this happens if you increase the minimum and maximum time? Also, the script output specifies that new Tor IP adresses are being used? I think the problem is that the server is refusing the request because there had been too many requests from the same IP adress. I will change the script to change the IP address in the case, but in the meantime you could check that the IP address is changing or increase the time between requests. I will let you know when I fix this

**Comment by zeroploitable** [comment] 2021-04-20 18:16
Hi ricardojoserf,

Thank you for your immediate response!

I already changed the MIN and MAX values of waiting to default, and it is working fine for the moment.
I will keep you posted if any issue appear, but most probably they are related to the time waiting interval.

**Comment by ricardojoserf** [comment] 2021-04-20 18:47
Great! Anyways I am trying to force the error to see if the script can now handle it. But if it keeps working fine for you feel free to close the issue ;)

**Comment by zeroploitable** [comment] 2021-04-20 22:01
It Happened again now unfortunatly. Find below the error output:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/socks.py", line 809, in connect
    negotiate(self, dest_addr, dest_port)
  File "/usr/lib/python3/dist-packages/socks.py", line 443, in _negotiate_SOCKS5
    self.proxy_peername, self.proxy_sockname = self._SOCKS5_request(
  File "/usr/lib/python3/dist-packages/socks.py", line 533, in _SOCKS5_request
    raise SOCKS5Error("{:#04x}: {}".format(status, error))
socks.SOCKS5Error: 0x01: General SOCKS server failure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
  File "/usr/lib/python3/dist-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/socks.py", line 814, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x01: General SOCKS server failure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1a1214a9a0>: Failed to establish a new connection: Socket error: 0x01: General SOCKS server failure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fs.*****.com.lb', port=443): Max retries exceeded with url: /adfs/ls/?username=test%40*****.com.lb&wa=wsignin1.0&wtrealm=urn%3Afederation%3AMicrosoftOnline&wctx= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1a1214a9a0>: Failed to establish a new connection: Socket error: 0x01: General SOCKS server failure'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/adfsbrute/adfsbrute.py", line 246, in <module>
    main()
  File "/opt/adfsbrute/adfsbrute.py", line 235, in main
    correct_user = check_dafs_user(dafs_url,credential,debug,proxy,test_credentials_file,str(counter), str(len(pairs)), new_ip)
  File "/opt/adfsbrute/adfsbrute.py", line 65, in check_dafs_user
    resp = requests.post(dafs_url, data = data, headers = headers, verify = False, proxies = proxy)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fs.*****.com.lb', port=443): Max retries exceeded with url: /adfs/ls/?username=test%40*****.com&wa=wsignin1.0&wtrealm=urn%3Afederation%3AMicrosoftOnline&wctx= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1a1214a9a0>: Failed to establish a new connection: Socket error: 0x01: General SOCKS server failure'))

**Comment by ricardojoserf** [comment] 2021-04-23 16:45
Hello @zeroploitable . I just pushed a commit which I am pretty sure that should solve this, sorry for the delay but it was a busy week. Please check if it works now for you and let me know when you can :)

**Comment by ricardojoserf** [comment] 2021-04-26 07:45
I close this issue as I think it is fixed with last commit, if not let me know and I will reopen it!

**Closed as completed by ricardojoserf** 2021-04-26 07:45 UTC
